CREATE TABLE TB_CARGO
(
   CODIGO         SMALLINT 	 	     NOT NULL,
   DESCRICAO      VARCHAR(30)            NOT NULL,
   CONSTRAINT     PK_CARGO PRIMARY KEY (CODIGO)
);


CREATE TABLE TB_SETOR
(
   CODIGO             SMALLINT            NOT NULL,
   DESCRICAO          VARCHAR(30)         NOT NULL,
   CONSTRAINT PK_SETOR PRIMARY KEY (CODIGO)
);


CREATE TABLE TB_CIDADE
(
   CODIGO             SMALLINT            NOT NULL,
   DESCRICAO          VARCHAR(30)         NOT NULL,
   CONSTRAINT PK_CIDADE PRIMARY KEY (CODIGO)
);


CREATE TABLE TB_FUNCIONARIO
(
   MATRICULA            INT               NOT NULL,
   NOME                 VARCHAR(50)       NOT NULL,
   LOGRADOURO           VARCHAR(50)       NOT NULL,
   NUMEROENDERECO       INT               ,
   COMPLENDERECO        VARCHAR(20)       ,
   BAIRRO               VARCHAR(30)       ,
   CIDADE               SMALLINT          NOT NULL,
   CEP                  CHAR(08)          NOT NULL,
   PONTOREFERENCIA      VARCHAR(60)      ,
   TELEFONE             VARCHAR(10)       DEFAULT '0000000000',
   E_MAIL               VARCHAR(60)      ,
   SEXO                 CHAR(01)          NOT NULL,
   ESTADOCIVIL          CHAR(01)          NOT NULL,
   DATANASCIMENTO       DATE              NOT NULL,
   CPF                  CHAR(11)          NOT NULL,
   DATAADMISSAO         DATE              NOT NULL,
   DATADEMISSAO         DATE             
);


CREATE TABLE TB_HISTORICO
(
   ANO        		SMALLINT          NOT NULL,
   MES		      SMALLINT          NOT NULL,
   MATRICULA            INT               NOT NULL,
   CARGO                SMALLINT          NOT NULL,
   SETOR                SMALLINT          NOT NULL,
   HORASMENSAIS         SMALLINT          NOT NULL,
   SALARIOBASE          NUMERIC(11,2)     NOT NULL
);

ALTER TABLE TB_FUNCIONARIO ADD  CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (MATRICULA) USING INDEX TABLESPACE TBS_INDICES;

ALTER TABLE TB_FUNCIONARIO ADD   CONSTRAINT FK_EMPREGADOCIDADE FOREIGN KEY(CIDADE)
                 REFERENCES TB_CIDADE(CODIGO);

ALTER TABLE TB_HISTORICO   ADD   CONSTRAINT PK_HISTORICO PRIMARY KEY (ANO, MES, MATRICULA) USING INDEX TABLESPACE TBS_INDICES;

ALTER TABLE TB_HISTORICO   ADD   CONSTRAINT FK_HISTORICO_FUNCIONARIO FOREIGN KEY(MATRICULA)
			                 REFERENCES TB_FUNCIONARIO(MATRICULA);

ALTER TABLE TB_HISTORICO   ADD   CONSTRAINT FK_HISTORICO_CARGO FOREIGN KEY(CARGO)
			                 REFERENCES TB_CARGO(CODIGO);

ALTER TABLE TB_HISTORICO   ADD   CONSTRAINT FK_HISTORICO_SETOR FOREIGN KEY(SETOR)
			                 REFERENCES TB_SETOR(CODIGO);

INSERT INTO TB_CARGO VALUES (1,'PROGRAMADOR');
INSERT INTO TB_CARGO VALUES (2,'ANALISTA');
INSERT INTO TB_CARGO VALUES (3,'GERENTE');
INSERT INTO TB_CARGO VALUES (4,'ADMINISTRADOR');
INSERT INTO TB_CARGO VALUES (5,'COPEIRA');


INSERT INTO TB_SETOR VALUES (1,'ADMINISTRAÇÃO');
INSERT INTO TB_SETOR VALUES (2,'PRODUÇÃO');
INSERT INTO TB_SETOR VALUES (3,'FINANCEIRO');
INSERT INTO TB_SETOR VALUES (4,'RH');
INSERT INTO TB_SETOR VALUES (5,'DESENVOLVIMENTO');

INSERT INTO TB_CIDADE VALUES (1,'SALVADOR');
INSERT INTO TB_CIDADE VALUES (2,'ITABUNA');
INSERT INTO TB_CIDADE VALUES (3,'LAURO DE FREITAS');

COMMIT;