SELECT * FROM USER_OBJECTS;

SELECT * FROM USER_OBJECTS WHERE OBJECT_TYPE = 'TABLE';

SELECT * FROM USER_TAB_COLUMNS;

SELECT * FROM
USER_OBJECTS,
USER_TAB_COLUMNS
WHERE TABLE_NAME = OBJECT_NAME
AND DATA_TYPE = 'NUMBER';